#!/bin/sh

# Make the interpreter intolerant to errors
set -o nounset
set -o errexit
set -o pipefail


# ===== Configuration


MEMORY_LIMIT_RATIO="0.9"


DEBUG_CLI_ARGS='-d display_errors=On -d display_startup_errors=On -d error_reporting=E_ALL'


# ===== Constants and functions


multiply() {
    local x="$1"
    local y="$2"

    awk -v "x=${x}" -v "y=${y}" 'BEGIN{ printf "%i" ,x * y }'
}


get_container_memory_bytes() {
    cgget -n --values-only --variable memory.limit_in_bytes /
}


get_host_memory_bytes() {
    free -b | egrep '^(Mem|Swap):' | awk '{i+=$2} END {print i}'
}


is_container_memory_limited() {
    [ "$(get_container_memory_bytes)" -lt "$(get_host_memory_bytes)" ]
}


get_cli_arg_for_memory_limit() {
    local cli_arg

    if is_container_memory_limited; then
        local container_memory_bytes="$(get_container_memory_bytes)"
        local memory_limit_bytes="$(multiply "${container_memory_bytes}" "${MEMORY_LIMIT_RATIO}" )"
        cli_arg="-d memory_limit=${memory_limit_bytes}"
    else
        cli_arg=""
    fi

    echo "${cli_arg}"
}


get_cli_args_for_debugging() {
    local cli_args

    if [[ "${DEBUG-}" == "true" ]]; then
        cli_args="${DEBUG_CLI_ARGS}"
    else
        cli_args=""
    fi

    echo "${cli_args}"
}


# ===== Main


export WORKER_PROCESSES="${WORKER_PROCESSES:-1}"
exec php-fpm \
    -c /etc/php5/php-fpm.conf \
    $(get_cli_arg_for_memory_limit) \
    $(get_cli_args_for_debugging) \
    $@
